---
site_name: JBook
site_description: All my notes
site_author: turf00
site_url: https://turf00.github.io/jbook
nav:
  - Introduction: index.md
  - Coding:
      - Coding: coding/coding.md
      - Git: coding/git.md
      - JVM:
        - Classloading: coding/jvm/classloading.md
        - Java Flight Recorder: coding/jvm/jfr.md
        - JVM: coding/jvm/jvm.md
        - JVM Assembly: coding/jvm/jvm-asm.md
        - JVM Flags: coding/jvm/jvm-flags.md
        - JVM Troubleshooting: coding/jvm/jvm-troubleshooting.md
        - Metaspace: coding/jvm/metaspace.md
        - Object Layout: coding/jvm/object-layout.md
        - Heap dump example: coding/jvm/heap-dump-analysis/heap-dump-tool-analysis.md
        - Leak Analysis: coding/jvm/heap-dump-analysis/leak-analysis.md
        - Async profiler: coding/jvm/async.md
      - Shell:
        - Bash Handling params: coding/shell/bash-handling-params.md
      - Training:
        - Async profiler: coding/training/async-profiler.md
  - Linux:
      - Monitoring: linux/monitoring.md
  - Contact: contact.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  logo: img/logo.jpg
  features:
    - navigation.instant
  palette:
    scheme: default
    primary: blue grey
    accent: light blue

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jbook

repo_name: turf00/jbook
repo_url: https://github.com/turf00/jbook
